[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "npm run start --workspace=backend"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10